### Read CSV from GitHub

In [ ]:
import pandas as pd

seasons = ["2020-2021", "2021-2022", "2022-2023", "2023-2024", "2024-2025", "2025-2026"]

file_types = ["standard", "shooting", "keeper", "playing_time", "misc"]

csvtypes = {
    "standard":     "Big-5-European-Leagues-Stats.csv",
    "shooting":     "Big-5-European-Leagues-Stats-Shooting.csv",
    "keeper":       "Big-5-European-Leagues-Stats-Keeper.csv",
    "playing_time": "Big-5-European-Leagues-Stats-Playing-Time.csv",
    "misc":         "Big-5-European-Leagues-Stats-Misc.csv",
}

dfs = {}
for season in seasons:
    for ftype, suffix in csvtypes.items():
        key = f"{ftype}_{season}"
        dfs[key] = pd.read_csv(f"{season}-{suffix}")
        print(f"[{key}] shape: {dfs[key].shape}")

[standard_2020-2021] shape: (2822, 26)
[shooting_2020-2021] shape: (2822, 20)
[keeper_2020-2021] shape: (208, 28)
[playing_time_2020-2021] shape: (3443, 26)
[misc_2020-2021] shape: (2822, 22)
[standard_2021-2022] shape: (2922, 26)
[shooting_2021-2022] shape: (2922, 20)
[keeper_2021-2022] shape: (218, 28)
[playing_time_2021-2022] shape: (3591, 26)
[misc_2021-2022] shape: (2922, 22)
[standard_2022-2023] shape: (2889, 26)
[shooting_2022-2023] shape: (2889, 20)
[keeper_2022-2023] shape: (208, 28)
[playing_time_2022-2023] shape: (3527, 26)
[misc_2022-2023] shape: (2889, 22)
[standard_2023-2024] shape: (2852, 26)
[shooting_2023-2024] shape: (2852, 20)
[keeper_2023-2024] shape: (203, 28)
[playing_time_2023-2024] shape: (3512, 26)
[misc_2023-2024] shape: (2852, 22)
[standard_2024-2025] shape: (2854, 26)
[shooting_2024-2025] shape: (2854, 20)
[keeper_2024-2025] shape: (212, 28)
[playing_time_2024-2025] shape: (3508, 26)
[misc_2024-2025] shape: (2854, 22)
[standard_2025-2026] shape: (2810, 26)
[shooting_2025-2026] shape: (2810, 20)
[keeper_2025-2026] shape: (184, 28)
[playing_time_2025-2026] shape: (3519, 26)
[misc_2025-2026] shape: (2810, 22)

In [ ]:
for season in seasons:
    short = f"{season.split('-')[0][2:]}_{season.split('-')[1][2:]}"
    for ftype in file_types:
        globals()[f"{ftype}_{short}"] = dfs[f"{ftype}_{season}"]

In [ ]:
shooting_25_26.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Standard_Gls,Standard_Sh,Standard_SoT,Standard_SoT%,Standard_Sh/90,Standard_SoT/90,Standard_G/Sh,Standard_G/SoT,Standard_PK,Standard_PKatt,Matches
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25-212,2000.0,26.2,4,43,16,37.2,1.64,0.61,0.09,0.25,0,0,Matches
1,2,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,20-009,2006.0,1.8,0,0,0,NaN,0.00,0.00,NaN,NaN,0,0,Matches
2,3,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,20-130,2006.0,7.6,2,17,4,23.5,2.25,0.53,0.12,0.50,0,0,Matches
3,4,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,26-186,1999.0,1.5,0,4,1,25.0,2.61,0.65,0.00,0.00,0,0,Matches
4,5,Himad Abdelli,dz ALG,MF,Angers,fr Ligue 1,26-186,1999.0,10.5,2,11,5,45.5,1.05,0.48,0.00,0.00,2,2,Matches

In [ ]:
keeper_25_26.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time_MP,Playing Time_Starts,...,Performance_D,Performance_L,Performance_CS,Performance_CS%,Penalty Kicks_PKatt,Penalty Kicks_PKA,Penalty Kicks_PKsv,Penalty Kicks_PKm,Penalty Kicks_Save%,Matches
0,1,Julen Agirrezabala,es ESP,GK,Valencia,es La Liga,25-147,2000,18,18,...,7,8,4,22.2,4,3,1,0,25.0,Matches
1,2,Alisson,br BRA,GK,Liverpool,eng Premier League,33-232,1992,25,25,...,7,5,8,32.0,2,2,0,0,0.0,Matches
2,3,Nícolas Andrade,br BRA,GK,Pisa,it Serie A,38-040,1988,6,6,...,0,5,0,0.0,1,0,0,1,NaN,Matches
3,4,Alphonse Areola,fr FRA,GK,West Ham United,eng Premier League,33-084,1993,20,20,...,5,11,0,0.0,6,5,0,1,0.0,Matches
4,5,Paul Argney,fr FRA,GK,Le Havre,fr Ligue 1,19-364,2006,1,1,...,0,0,0,0.0,0,0,0,0,NaN,Matches

In [ ]:
misc_25_26.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,90s,Performance_CrdY,...,Performance_Fls,Performance_Fld,Performance_Off,Performance_Crs,Performance_Int,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Matches
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25-212,2000.0,26.2,2,...,19,50,5,37,17,26,NaN,NaN,0,Matches
1,2,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,20-009,2006.0,1.8,0,...,3,1,0,3,2,4,NaN,NaN,0,Matches
2,3,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,20-130,2006.0,7.6,0,...,7,3,2,30,3,3,NaN,NaN,0,Matches
3,4,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,26-186,1999.0,1.5,1,...,3,0,0,1,2,1,NaN,NaN,0,Matches
4,5,Himad Abdelli,dz ALG,MF,Angers,fr Ligue 1,26-186,1999.0,10.5,1,...,16,12,1,9,13,17,NaN,NaN,0,Matches

In [ ]:
playing_time_25_26.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time_MP,Playing Time_Min,...,Subs_Subs,Subs_Mn/Sub,Subs_unSub,Team Success_PPM,Team Success_onG,Team Success_onGA,Team Success_+/-,Team Success_+/-90,Team Success_On-Off,Matches
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25-212,2000.0,36,2360.0,...,7,21.0,1,1.22,35.0,29.0,6.0,0.23,1.16,Matches
1,2,Jerome Abbey,eng ENG,MF,Wolves,eng Premier League,16-248,2009.0,0,NaN,...,0,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Matches
2,3,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,20-009,2006.0,3,164.0,...,1,45.0,12,1.00,2.0,4.0,-2.0,-1.10,-1.07,Matches
3,4,Keyliane Abdallah,fr FRA,FW,Marseille,fr Ligue 1,20-047,2006.0,0,NaN,...,0,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,Matches
4,5,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,20-130,2006.0,22,681.0,...,18,21.0,15,1.55,17.0,12.0,5.0,0.66,0.69,Matches

In [ ]:
standard_25_26.head()

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time_MP,Playing Time_Starts,...,Performance_PK,Performance_PKatt,Performance_CrdY,Performance_CrdR,Per 90 Minutes_Gls,Per 90 Minutes_Ast,Per 90 Minutes_G+A,Per 90 Minutes_G-PK,Per 90 Minutes_G+A-PK,Matches
0,1,Brenden Aaronson,us USA,"MF,FW",Leeds United,eng Premier League,25-212,2000.0,36,29,...,0,0,2,0,0.15,0.19,0.34,0.15,0.34,Matches
1,2,Zach Abbott,eng ENG,DF,Nottingham Forest,eng Premier League,20-009,2006.0,3,2,...,0,0,0,0,0.00,0.00,0.00,0.00,0.00,Matches
2,3,Jones El-Abdellaoui,ma MAR,"MF,FW",Celta Vigo,es La Liga,20-130,2006.0,22,4,...,0,0,0,0,0.26,0.00,0.26,0.26,0.26,Matches
3,4,Himad Abdelli,dz ALG,MF,Marseille,fr Ligue 1,26-186,1999.0,8,1,...,0,0,1,0,0.00,0.00,0.00,0.00,0.00,Matches
4,5,Himad Abdelli,dz ALG,MF,Angers,fr Ligue 1,26-186,1999.0,13,11,...,2,2,1,0,0.19,0.00,0.19,0.00,0.00,Matches

In [ ]:
short = "25_26"

all_cols = {
    "standard":     set(globals()[f"standard_{short}"].columns),
    "shooting":     set(globals()[f"shooting_{short}"].columns),
    "keeper":       set(globals()[f"keeper_{short}"].columns),
    "playing_time": set(globals()[f"playing_time_{short}"].columns),
    "misc":         set(globals()[f"misc_{short}"].columns),
}

common = set.intersection(*all_cols.values())
print("Common columns:", common)

for name, cols in all_cols.items():
    print(f"\n{name} only: {sorted(cols - common)}")

Common columns: {'Player', 'Squad', 'Comp', 'Rk', 'Nation', 'Matches', 'Age', 'Born', 'Pos'}

standard only: ['Per 90 Minutes_Ast', 'Per 90 Minutes_G+A', 'Per 90 Minutes_G+A-PK', 'Per 90 Minutes_G-PK', 'Per 90 Minutes_Gls', 'Performance_Ast', 'Performance_CrdR', 'Performance_CrdY', 'Performance_G+A', 'Performance_G-PK', 'Performance_Gls', 'Performance_PK', 'Performance_PKatt', 'Playing Time_90s', 'Playing Time_MP', 'Playing Time_Min', 'Playing Time_Starts']

shooting only: ['90s', 'Standard_G/Sh', 'Standard_G/SoT', 'Standard_Gls', 'Standard_PK', 'Standard_PKatt', 'Standard_Sh', 'Standard_Sh/90', 'Standard_SoT', 'Standard_SoT%', 'Standard_SoT/90']

keeper only: ['90s', 'Penalty Kicks_PKA', 'Penalty Kicks_PKatt', 'Penalty Kicks_PKm', 'Penalty Kicks_PKsv', 'Penalty Kicks_Save%', 'Performance_CS', 'Performance_CS%', 'Performance_D', 'Performance_GA', 'Performance_GA90', 'Performance_L', 'Performance_Save%', 'Performance_Saves', 'Performance_SoTA', 'Performance_W', 'Playing Time_MP', 'Playing Time_Min', 'Playing Time_Starts']

playing_time only: ['Playing Time_90s', 'Playing Time_MP', 'Playing Time_Min', 'Playing Time_Min%', 'Playing Time_Mn/MP', 'Starts_Compl', 'Starts_Mn/Start', 'Starts_Starts', 'Subs_Mn/Sub', 'Subs_Subs', 'Subs_unSub', 'Team Success_+/-', 'Team Success_+/-90', 'Team Success_On-Off', 'Team Success_PPM', 'Team Success_onG', 'Team Success_onGA']

misc only: ['90s', 'Performance_2CrdY', 'Performance_CrdR', 'Performance_CrdY', 'Performance_Crs', 'Performance_Fld', 'Performance_Fls', 'Performance_Int', 'Performance_OG', 'Performance_Off', 'Performance_PKcon', 'Performance_PKwon', 'Performance_TklW']

In [ ]:
JOIN_KEYS = ["Player", "Squad", "Born"]

def merge_season(short):
    base = globals()[f"standard_{short}"].copy()

    others = {
        "shooting":     globals()[f"shooting_{short}"],
        "keeper":       globals()[f"keeper_{short}"],
        "playing_time": globals()[f"playing_time_{short}"],
        "misc":         globals()[f"misc_{short}"],
    }

    for ftype, df in others.items():
        base = base.merge(df, on=JOIN_KEYS, how="outer" ,suffixes=("", f"_{ftype}"))

    return base

merged_25_26 = merge_season("25_26")
print(merged_25_26.shape)
merged_25_26.head()

(3519, 110)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time_MP,Playing Time_Starts,...,Performance_Fls,Performance_Fld,Performance_Off,Performance_Crs,Performance_Int,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Matches_misc
0,126.0,Aaron Anselmino,ar ARG,DF,Dortmund,de Bundesliga,21-023,2005.0,6.0,4.0,...,6.0,3.0,0.0,2.0,7.0,8.0,NaN,NaN,0.0,Matches
1,127.0,Aaron Anselmino,ar ARG,DF,Strasbourg,fr Ligue 1,21-023,2005.0,3.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,Matches
2,1142.0,Aaron Hickey,sct SCO,"DF,MF",Brentford,eng Premier League,23-346,2002.0,20.0,8.0,...,6.0,9.0,0.0,4.0,7.0,7.0,NaN,NaN,0.0,Matches
3,NaN,Aaron Mayol,NaN,NaN,Valencia,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2156.0,Aaron Ramsdale,eng ENG,GK,Newcastle United,eng Premier League,28-008,1998.0,12.0,11.0,...,0.0,1.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,Matches

In [ ]:
merged_25_26.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3519 entries, 0 to 3518
Data columns (total 110 columns):
 #    Column                         Non-Null Count  Dtype
---   ------                         --------------  -----
 0    Rk                             2810 non-null   float64
 1    Player                         3519 non-null   object
 2    Nation                         2807 non-null   object
 3    Pos                            2810 non-null   object
 4    Squad                          3519 non-null   object
 5    Comp                           2810 non-null   object
 6    Age                            2808 non-null   object
 7    Born                           3509 non-null   float64
 8    Playing Time_MP                2810 non-null   float64
 9    Playing Time_Starts            2810 non-null   float64
 10   Playing Time_Min               2810 non-null   float64
 11   Playing Time_90s               2810 non-null   float64
 12   Performance_Gls                2810 non-null   float64
 13   Performance_Ast                2810 non-null   float64
 14   Performance_G+A                2810 non-null   float64
 15   Performance_G-PK               2810 non-null   float64
 16   Performance_PK                 2810 non-null   float64
 17   Performance_PKatt              2810 non-null   float64
 18   Performance_CrdY               2810 non-null   float64
 19   Performance_CrdR               2810 non-null   float64
 20   Per 90 Minutes_Gls             2810 non-null   float64
 21   Per 90 Minutes_Ast             2810 non-null   float64
 22   Per 90 Minutes_G+A             2810 non-null   float64
 23   Per 90 Minutes_G-PK            2810 non-null   float64
 24   Per 90 Minutes_G+A-PK          2810 non-null   float64
 25   Matches                        2810 non-null   object
 26   Rk_shooting                    2810 non-null   float64
 27   Nation_shooting                2807 non-null   object
 28   Pos_shooting                   2810 non-null   object
 29   Comp_shooting                  2810 non-null   object
 30   Age_shooting                   2808 non-null   object
 31   90s                            2810 non-null   float64
 32   Standard_Gls                   2810 non-null   float64
 33   Standard_Sh                    2810 non-null   float64
 34   Standard_SoT                   2810 non-null   float64
 35   Standard_SoT%                  2332 non-null   float64
 36   Standard_Sh/90                 2810 non-null   float64
 37   Standard_SoT/90                2810 non-null   float64
 38   Standard_G/Sh                  2332 non-null   float64
 39   Standard_G/SoT                 2000 non-null   float64
 40   Standard_PK                    2810 non-null   float64
 41   Standard_PKatt                 2810 non-null   float64
 42   Matches_shooting               2810 non-null   object
 43   Rk_keeper                      184 non-null    float64
 44   Nation_keeper                  184 non-null    object
 45   Pos_keeper                     184 non-null    object
 46   Comp_keeper                    184 non-null    object
 47   Age_keeper                     184 non-null    object
 48   Playing Time_MP_keeper         184 non-null    float64
 49   Playing Time_Starts_keeper     184 non-null    float64
 50   Playing Time_Min_keeper        184 non-null    float64
 51   90s_keeper                     184 non-null    float64
 52   Performance_GA                 184 non-null    float64
 53   Performance_GA90               184 non-null    float64
 54   Performance_SoTA               184 non-null    float64
 55   Performance_Saves              184 non-null    float64
 56   Performance_Save%              183 non-null    float64
 57   Performance_W                  184 non-null    float64
 58   Performance_D                  184 non-null    float64
 59   Performance_L                  184 non-null    float64
 60   Performance_CS                 184 non-null    float64
 61   Performance_CS%                181 non-null    float64
 62   Penalty Kicks_PKatt            184 non-null    float64
 63   Penalty Kicks_PKA              184 non-null    float64
 64   Penalty Kicks_PKsv             184 non-null    float64
 65   Penalty Kicks_PKm              184 non-null    float64
 66   Penalty Kicks_Save%            137 non-null    float64
 67   Matches_keeper                 184 non-null    object
 68   Rk_playing_time                3519 non-null   int64
 69   Nation_playing_time            3507 non-null   object
 70   Pos_playing_time               3518 non-null   object
 71   Comp_playing_time              3519 non-null   object
 72   Age_playing_time               3509 non-null   object
 73   Playing Time_MP_playing_time   3519 non-null   int64
 74   Playing Time_Min_playing_time  2810 non-null   float64
 75   Playing Time_Mn/MP             2810 non-null   float64
 76   Playing Time_Min%              2814 non-null   float64
 77   Playing Time_90s_playing_time  2814 non-null   float64
 78   Starts_Starts                  3519 non-null   int64
 79   Starts_Mn/Start                2459 non-null   float64
 80   Starts_Compl                   3519 non-null   int64
 81   Subs_Subs                      3519 non-null   int64
 82   Subs_Mn/Sub                    2436 non-null   float64
 83   Subs_unSub                     3519 non-null   int64
 84   Team Success_PPM               2814 non-null   float64
 85   Team Success_onG               2814 non-null   float64
 86   Team Success_onGA              2814 non-null   float64
 87   Team Success_+/-               2814 non-null   float64
 88   Team Success_+/-90             2810 non-null   float64
 89   Team Success_On-Off            2779 non-null   float64
 90   Matches_playing_time           3519 non-null   object
 91   Rk_misc                        2810 non-null   float64
 92   Nation_misc                    2807 non-null   object
 93   Pos_misc                       2810 non-null   object
 94   Comp_misc                      2810 non-null   object
 95   Age_misc                       2808 non-null   object
 96   90s_misc                       2810 non-null   float64
 97   Performance_CrdY_misc          2810 non-null   float64
 98   Performance_CrdR_misc          2810 non-null   float64
 99   Performance_2CrdY              2810 non-null   float64
 100  Performance_Fls                2810 non-null   float64
 101  Performance_Fld                2810 non-null   float64
 102  Performance_Off                2810 non-null   float64
 103  Performance_Crs                2810 non-null   float64
 104  Performance_Int                2810 non-null   float64
 105  Performance_TklW               2810 non-null   float64
 106  Performance_PKwon              0 non-null      float64
 107  Performance_PKcon              0 non-null      float64
 108  Performance_OG                 2810 non-null   float64
 109  Matches_misc                   2810 non-null   object
dtypes: float64(77), int64(6), object(27)
memory usage: 3.0+ MB

In [ ]:
seasons_short = [f"{s.split('-')[0][2:]}_{s.split('-')[1][2:]}" for s in seasons]

merged_dfs = {}
for short in seasons_short:
    merged_dfs[short] = merge_season(short)
    print(f"[{short}] shape: {merged_dfs[short].shape}")

[20_21] shape: (3443, 110)
[21_22] shape: (3591, 110)
[22_23] shape: (3527, 110)
[23_24] shape: (3512, 110)
[24_25] shape: (3508, 110)
[25_26] shape: (3519, 110)

In [ ]:
for short, season in zip(seasons_short, seasons):
    merged_dfs[short]["season"] = season

final_df = pd.concat(merged_dfs.values(), ignore_index=True)
print(final_df.shape)
final_df.head(20)

(21100, 111)

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time_MP,Playing Time_Starts,...,Performance_Fld,Performance_Off,Performance_Crs,Performance_Int,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Matches_misc,season
0,541.0,Aaron Connolly,ie IRL,"FW,MF",Brighton,eng Premier League,20.0,2000.0,17.0,9.0,...,16.0,8.0,2.0,0.0,3.0,NaN,NaN,0.0,Matches,2020-2021
1,584.0,Aaron Cresswell,eng ENG,DF,West Ham United,eng Premier League,30.0,1989.0,36.0,36.0,...,18.0,0.0,208.0,33.0,15.0,NaN,NaN,0.0,Matches,2020-2021
2,1138.0,Aaron Hickey,sct SCO,"DF,MF",Bologna,it Serie A,18.0,2002.0,11.0,10.0,...,15.0,0.0,8.0,16.0,8.0,NaN,NaN,0.0,Matches,2020-2021
3,NaN,Aaron Kamardin,NaN,NaN,Marseille,NaN,NaN,2002.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-2021
4,1462.0,Aaron Leya Iseka,be BEL,FW,Metz,fr Ligue 1,22.0,1997.0,21.0,12.0,...,12.0,2.0,2.0,0.0,3.0,NaN,NaN,0.0,Matches,2020-2021
5,2166.0,Aaron Ramsdale,eng ENG,GK,Sheffield United,eng Premier League,22.0,1998.0,38.0,38.0,...,5.0,0.0,0.0,2.0,1.0,NaN,NaN,0.0,Matches,2020-2021
6,2167.0,Aaron Ramsey,wls WAL,MF,Juventus,it Serie A,29.0,1990.0,22.0,13.0,...,18.0,3.0,22.0,9.0,15.0,NaN,NaN,0.0,Matches,2020-2021
7,2728.0,Aaron Wan-Bissaka,cd COD,DF,Manchester Utd,eng Premier League,22.0,1997.0,34.0,34.0,...,14.0,1.0,62.0,61.0,52.0,NaN,NaN,0.0,Matches,2020-2021
8,818.0,Aarón Escandell,es ESP,GK,Granada,es La Liga,24.0,1995.0,5.0,5.0,...,0.0,0.0,0.0,0.0,1.0,NaN,NaN,0.0,Matches,2020-2021
9,1626.0,Aarón Martín,es ESP,DF,Celta Vigo,es La Liga,23.0,1997.0,19.0,17.0,...,15.0,3.0,53.0,12.0,25.0,NaN,NaN,0.0,Matches,2020-2021
10,1625.0,Aarón Martín,es ESP,"MF,DF",Mainz 05,de Bundesliga,23.0,1997.0,5.0,3.0,...,0.0,0.0,22.0,4.0,2.0,NaN,NaN,0.0,Matches,2020-2021
11,1201.0,Abass Issah,gh GHA,"FW,MF",Mainz 05,de Bundesliga,21.0,1998.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,NaN,0.0,Matches,2020-2021
12,1553.0,Abdallahi Mahmoud,mr MTN,MF,Alavés,es La Liga,20.0,2000.0,2.0,1.0,...,1.0,0.0,0.0,1.0,2.0,NaN,NaN,0.0,Matches,2020-2021
13,NaN,Abdel Abqar,NaN,NaN,Alavés,NaN,NaN,1999.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-2021
14,693.0,Abdou Diallo,sn SEN,DF,Paris Saint-Germain,fr Ligue 1,24.0,1996.0,22.0,17.0,...,9.0,1.0,12.0,25.0,13.0,NaN,NaN,0.0,Matches,2020-2021
15,NaN,Abdoul Bane,NaN,NaN,Parma,NaN,NaN,2001.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-2021
16,1260.0,Abdoul Kader Bamba,fr FRA,MF,Nantes,fr Ligue 1,26.0,1994.0,29.0,6.0,...,41.0,0.0,38.0,10.0,4.0,NaN,NaN,0.0,Matches,2020-2021
17,689.0,Abdoulay Diaby,ml MLI,"FW,MF",Getafe,es La Liga,29.0,1991.0,1.0,0.0,...,0.0,0.0,2.0,0.0,0.0,NaN,NaN,0.0,Matches,2020-2021
18,NaN,Abdoulaye Bakayoko,NaN,NaN,Saint-Étienne,NaN,NaN,2002.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2020-2021
19,185.0,Abdoulaye Bamba,ci CIV,DF,Angers,fr Ligue 1,30.0,1990.0,16.0,16.0,...,7.0,0.0,49.0,19.0,17.0,NaN,NaN,0.0,Matches,2020-2021

In [ ]:
final_df[final_df["Player"].str.contains("Pedri", case=False, na=False)]

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time_MP,Playing Time_Starts,...,Performance_Fld,Performance_Off,Performance_Crs,Performance_Int,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Matches_misc,season
2580,2023.0,Pedri,es ESP,MF,Barcelona,es La Liga,17.0,2002.0,37.0,28.0,...,42.0,0.0,12.0,30.0,27.0,NaN,NaN,0.0,Matches,2020-2021
6182,2062.0,Pedri,es ESP,MF,Barcelona,es La Liga,18.0,2002.0,12.0,10.0,...,17.0,0.0,17.0,5.0,13.0,NaN,NaN,0.0,Matches,2021-2022
9732,2061.0,Pedri,es ESP,MF,Barcelona,es La Liga,19.0,2002.0,26.0,22.0,...,43.0,4.0,27.0,13.0,21.0,NaN,NaN,0.0,Matches,2022-2023
13272,2061.0,Pedri,es ESP,"MF,FW",Barcelona,es La Liga,20.0,2002.0,24.0,16.0,...,22.0,1.0,9.0,14.0,22.0,NaN,NaN,0.0,Matches,2023-2024
16784,2061.0,Pedri,es ESP,MF,Barcelona,es La Liga,21.0,2002.0,37.0,35.0,...,51.0,2.0,57.0,29.0,32.0,NaN,NaN,0.0,Matches,2024-2025
20287,2054.0,Pedri,es ESP,MF,Barcelona,es La Liga,23-178,2002.0,29.0,23.0,...,43.0,1.0,12.0,24.0,33.0,NaN,NaN,0.0,Matches,2025-2026

In [ ]:
final_df[final_df["Player"].str.contains("Gavi", case=False, na=False)]

,Rk,Player,Nation,Pos,Squad,Comp,Age,Born,Playing Time_MP,Playing Time_Starts,...,Performance_Fld,Performance_Off,Performance_Crs,Performance_Int,Performance_TklW,Performance_PKwon,Performance_PKcon,Performance_OG,Matches_misc,season
4584,969.0,Gavi,es ESP,"MF,FW",Barcelona,es La Liga,16.0,2004.0,34.0,28.0,...,69.0,12.0,49.0,29.0,19.0,NaN,NaN,0.0,Matches,2021-2022
8158,998.0,Gavi,es ESP,"MF,FW",Barcelona,es La Liga,17.0,2004.0,36.0,30.0,...,72.0,9.0,39.0,19.0,33.0,NaN,NaN,0.0,Matches,2022-2023
8159,251.0,Gavin Bazunu,ie IRL,GK,Southampton,eng Premier League,20.0,2002.0,32.0,32.0,...,2.0,0.0,0.0,1.0,0.0,NaN,NaN,0.0,Matches,2022-2023
11706,954.0,Gavi,es ESP,"MF,FW",Barcelona,es La Liga,18.0,2004.0,12.0,10.0,...,23.0,4.0,8.0,8.0,23.0,NaN,NaN,0.0,Matches,2023-2024
11707,NaN,Gavin Kilkenny,NaN,NaN,Bournemouth,NaN,NaN,2000.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2023-2024
15232,979.0,Gavi,es ESP,MF,Barcelona,es La Liga,19.0,2004.0,26.0,14.0,...,27.0,1.0,8.0,10.0,23.0,NaN,NaN,0.0,Matches,2024-2025
18718,958.0,Gavi,es ESP,MF,Barcelona,es La Liga,21-290,2004.0,10.0,6.0,...,12.0,0.0,1.0,3.0,7.0,NaN,NaN,0.0,Matches,2025-2026

In [ ]:
final_df[final_df["Player"].str.contains("Pedri", case=False, na=False)][["Player", "Age", "season"]]

      Player     Age     season
2580   Pedri    17.0  2020-2021
6182   Pedri    18.0  2021-2022
9732   Pedri    19.0  2022-2023
13272  Pedri    20.0  2023-2024
16784  Pedri    21.0  2024-2025
20287  Pedri  23-178  2025-2026

In [ ]:
final_df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21100 entries, 0 to 21099
Data columns (total 109 columns):
 #    Column                         Non-Null Count  Dtype
---   ------                         --------------  -----
 0    Player                         21100 non-null  object
 1    Nation                         17141 non-null  object
 2    Pos                            17149 non-null  object
 3    Squad                          21100 non-null  object
 4    Comp                           17149 non-null  object
 5    Age                            17146 non-null  object
 6    Born                           21084 non-null  float64
 7    Playing Time_MP                17149 non-null  float64
 8    Playing Time_Starts            17149 non-null  float64
 9    Playing Time_Min               17149 non-null  float64
 10   Playing Time_90s               17149 non-null  float64
 11   Performance_Gls                17149 non-null  float64
 12   Performance_Ast                17149 non-null  float64
 13   Performance_G+A                17149 non-null  float64
 14   Performance_G-PK               17149 non-null  float64
 15   Performance_PK                 17149 non-null  float64
 16   Performance_PKatt              17149 non-null  float64
 17   Performance_CrdY               17149 non-null  float64
 18   Performance_CrdR               17149 non-null  float64
 19   Per 90 Minutes_Gls             17149 non-null  float64
 20   Per 90 Minutes_Ast             17149 non-null  float64
 21   Per 90 Minutes_G+A             17149 non-null  float64
 22   Per 90 Minutes_G-PK            17149 non-null  float64
 23   Per 90 Minutes_G+A-PK          17149 non-null  float64
 24   Rk_shooting                    17149 non-null  float64
 25   Nation_shooting                17141 non-null  object
 26   Pos_shooting                   17149 non-null  object
 27   Comp_shooting                  17149 non-null  object
 28   Age_shooting                   17146 non-null  object
 29   90s                            17149 non-null  float64
 30   Standard_Gls                   17149 non-null  float64
 31   Standard_Sh                    17149 non-null  float64
 32   Standard_SoT                   17149 non-null  float64
 33   Standard_SoT%                  14006 non-null  float64
 34   Standard_Sh/90                 17149 non-null  float64
 35   Standard_SoT/90                17149 non-null  float64
 36   Standard_G/Sh                  14006 non-null  float64
 37   Standard_G/SoT                 11957 non-null  float64
 38   Standard_PK                    17149 non-null  float64
 39   Standard_PKatt                 17149 non-null  float64
 40   Matches_shooting               17149 non-null  object
 41   Rk_keeper                      1233 non-null   float64
 42   Nation_keeper                  1233 non-null   object
 43   Pos_keeper                     1233 non-null   object
 44   Comp_keeper                    1233 non-null   object
 45   Age_keeper                     1233 non-null   object
 46   Playing Time_MP_keeper         1233 non-null   float64
 47   Playing Time_Starts_keeper     1233 non-null   float64
 48   Playing Time_Min_keeper        1233 non-null   float64
 49   90s_keeper                     1233 non-null   float64
 50   Performance_GA                 1233 non-null   float64
 51   Performance_GA90               1233 non-null   float64
 52   Performance_SoTA               1233 non-null   float64
 53   Performance_Saves              1233 non-null   float64
 54   Performance_Save%              1209 non-null   float64
 55   Performance_W                  1233 non-null   float64
 56   Performance_D                  1233 non-null   float64
 57   Performance_L                  1233 non-null   float64
 58   Performance_CS                 1233 non-null   float64
 59   Performance_CS%                1174 non-null   float64
 60   Penalty Kicks_PKatt            1233 non-null   float64
 61   Penalty Kicks_PKA              1233 non-null   float64
 62   Penalty Kicks_PKsv             1233 non-null   float64
 63   Penalty Kicks_PKm              1233 non-null   float64
 64   Penalty Kicks_Save%            862 non-null    float64
 65   Matches_keeper                 1233 non-null   object
 66   Rk_playing_time                21100 non-null  int64
 67   Nation_playing_time            21068 non-null  object
 68   Pos_playing_time               21095 non-null  object
 69   Comp_playing_time              21100 non-null  object
 70   Age_playing_time               21084 non-null  object
 71   Playing Time_MP_playing_time   21100 non-null  int64
 72   Playing Time_Min_playing_time  17149 non-null  float64
 73   Playing Time_Mn/MP             17149 non-null  float64
 74   Playing Time_Min%              17173 non-null  float64
 75   Playing Time_90s_playing_time  17173 non-null  float64
 76   Starts_Starts                  21100 non-null  int64
 77   Starts_Mn/Start                14878 non-null  float64
 78   Starts_Compl                   20869 non-null  float64
 79   Subs_Subs                      21100 non-null  int64
 80   Subs_Mn/Sub                    14674 non-null  float64
 81   Subs_unSub                     21100 non-null  int64
 82   Team Success_PPM               17164 non-null  float64
 83   Team Success_onG               17173 non-null  float64
 84   Team Success_onGA              17173 non-null  float64
 85   Team Success_+/-               17173 non-null  float64
 86   Team Success_+/-90             17149 non-null  float64
 87   Team Success_On-Off            17020 non-null  float64
 88   Matches_playing_time           21100 non-null  object
 89   Rk_misc                        17149 non-null  float64
 90   Nation_misc                    17141 non-null  object
 91   Pos_misc                       17149 non-null  object
 92   Comp_misc                      17149 non-null  object
 93   Age_misc                       17146 non-null  object
 94   90s_misc                       17149 non-null  float64
 95   Performance_CrdY_misc          17149 non-null  float64
 96   Performance_CrdR_misc          17149 non-null  float64
 97   Performance_2CrdY              17149 non-null  float64
 98   Performance_Fls                17149 non-null  float64
 99   Performance_Fld                17149 non-null  float64
 100  Performance_Off                17149 non-null  float64
 101  Performance_Crs                17149 non-null  float64
 102  Performance_Int                17149 non-null  float64
 103  Performance_TklW               17149 non-null  float64
 104  Performance_PKwon              0 non-null      float64
 105  Performance_PKcon              0 non-null      float64
 106  Performance_OG                 17149 non-null  float64
 107  Matches_misc                   17149 non-null  object
 108  season                         21100 non-null  object
dtypes: float64(77), int64(5), object(27)
memory usage: 17.5+ MB

In [ ]:
final_df.to_csv("final_df.csv", index=False)